module.exports = {
  content: ["./index.html", "./src/**/*.{js,ts,jsx,tsx}"],
  theme: {
    extend: {
      backgroundImage: {
        "hero-pattern": "url('http://www.w3.org/2000/svg')",
      },
      colors: {
        primary: "#FBFBFB",
        primaryTwo: "#FFFFFF",
        primaryGray: "#E1E1E1",
        primaryBlue: "#0073C6",
        primaryLightBlue: "#8495B8",
        primaryPurple: "#5E006C",
        primaryOrange: "#FF9209",
        primaryGreen: "#86D5AD",
        darknavy: "#141D2C",
        secondaryGreen: "#00ff00",
        frontBlue: "#02071C",
      },
      fontFamily: {
        mulish: ["Mulish", "sans-serif"],
      },
    },
  },
  plugins: [require("daisyui")],
  daisyui: {
    themes: [
      "light",
      "dark",
      "cupcake",
      "bumblebee",
      "emerald",
      "corporate",
      "synthwave",
      "retro",
      "cyberpunk",
      "valentine",
      "halloween",
      "garden",
      "forest",
      "aqua",
      "lofi",
      "pastel",
      "fantasy",
      "wireframe",
      "black",
      "luxury",
      "dracula",
      "cmyk",
      "autumn",
      "business",
      "acid",
      "lemonade",
      "night",
      "coffee",
      "winter",
      "dim",
      "nord",
      "sunset",
    ],
  },
};
